name-template: 'WebSocket Lean v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: $MAJOR.$MINOR.$PATCH
categories:
  - title: '🚀 Features'
    labels: ['feature', 'enhancement']
  - title: '🐞 Fixes'
    labels: ['bug', 'fix']
  - title: '🧪 Tests'
    labels: ['test']
  - title: '🧰 Maintenance'
    labels: ['chore', 'deps', 'refactor']
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
change-title-escapes: ''
autolabeler: []
exclude-labels: ['skip-changelog']
template: |
  ## Changes
  $CHANGES
